PrimeiraAppWeb_2TDSPF/PrimeiraAppWeb_2TDSPF/Models/Boardgame.cs
using System.ComponentModel.DataAnnotations;

namespace PrimeiraAppWeb_2TDSPF.Models;

public class Boardgame
{
    [Key]
    public int Id { get; set; }
    [Required]
    public string? Name { get; set; }
    public string? Description { get; set; }
}

PrimeiraAppWeb_2TDSPF/PrimeiraAppWeb_2TDSPF/Models/ErrorViewModel.cs
namespace PrimeiraAppWeb_2TDSPF.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

PrimeiraAppWeb_2TDSPF/PrimeiraAppWeb_2TDSPF/Controllers/BoardgameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PrimeiraAppWeb_2TDSPF.Data;
using PrimeiraAppWeb_2TDSPF.Models;

namespace PrimeiraAppWeb_2TDSPF.Controllers
{
    public class BoardgameController : Controller
    {
        private readonly BoardgameDbContext _context;

        public BoardgameController(BoardgameDbContext context)
        {
            _context = context;
        }

        // GET: Boardgame
        public async Task<IActionResult> Index()
        {
            return View(await _context.Boardgames.ToListAsync());
        }

        // GET: Boardgame/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var boardgame = await _context.Boardgames
                .FirstOrDefaultAsync(m => m.Id == id);
            if (boardgame == null)
            {
                return NotFound();
            }

            return View(boardgame);
        }
        
        // Mantemos o mesmo exemplo de controller anterior, adequado para resposta a chamadas HTTP GET
        [HttpGet]
        public async Task<ActionResult> TopRatedGames()
        {
            var games = await _context.Boardgames
                .OrderByDescending(g => g.Id)
                .Take(1)
                .ToListAsync();
            return PartialView("_Top", games);
        }

        // GET: Boardgame/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Boardgame/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description")] Boardgame boardgame)
        {
            if (ModelState.IsValid)
            {
                _context.Add(boardgame);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(boardgame);
        }

        // GET: Boardgame/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var boardgame = await _context.Boardgames.FindAsync(id);
            if (boardgame == null)
            {
                return NotFound();
            }
            return View(boardgame);
        }

        // POST: Boardgame/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description")] Boardgame boardgame)
        {
            if (id != boardgame.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(boardgame);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BoardgameExists(boardgame.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(boardgame);
        }

        // GET: Boardgame/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var boardgame = await _context.Boardgames
                .FirstOrDefaultAsync(m => m.Id == id);
            if (boardgame == null)
            {
                return NotFound();
            }

            return View(boardgame);
        }

        // POST: Boardgame/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var boardgame = await _context.Boardgames.FindAsync(id);
            if (boardgame != null)
            {
                _context.Boardgames.Remove(boardgame);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BoardgameExists(int id)
        {
            return _context.Boardgames.Any(e => e.Id == id);
        }
    }
}

PrimeiraAppWeb_2TDSPF/PrimeiraAppWeb_2TDSPF/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using PrimeiraAppWeb_2TDSPF.Models;

namespace PrimeiraAppWeb_2TDSPF.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    public IActionResult Contact()
    {
        return View();
    }

    public ContentResult TesteTexto()
    {
        return Content("Texto de teste");
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

PrimeiraAppWeb_2TDSPF/PrimeiraAppWeb_2TDSPF/Views/Boardgame/Create.cshtml
@model PrimeiraAppWeb_2TDSPF.Models.Boardgame

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Boardgame</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


PrimeiraAppWeb_2TDSPF/PrimeiraAppWeb_2TDSPF/Views/Boardgame/Delete.cshtml
@model PrimeiraAppWeb_2TDSPF.Models.Boardgame

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Boardgame</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PrimeiraAppWeb_2TDSPF/PrimeiraAppWeb_2TDSPF/Views/Boardgame/Details.cshtml
@model PrimeiraAppWeb_2TDSPF.Models.Boardgame

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card">
    <div class="row g-0">
        <div class="col-md-4">
            <img src="https://cf.geekdo-images.com/x3zxjr-Vw5iU4yDPg70Jgw__itemrep/img/giNUMut4HAl-zWyQkGG0YchmuLI=/fit-in/246x300/filters:strip_icc()/pic3490053.jpg" class="img-fluid rounded-start" alt="...">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title"> @Html.DisplayFor(model => model.Name)</h5>
                <p class="card-text">@Html.DisplayFor(model => model.Description)</p>
                <a href="#" class="btn btn-info">Buy a copy</a>
                <a href="#" class="btn btn-primary">Add to collection</a>
                <a href="#" class="btn btn-secondary">Log play</a>
                <a href="#" class="btn btn-secondary">4.9K</a>
                <br/>
                <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
                <a asp-action="Index">Back to List</a>
            </div>
            
        </div>
    </div>
</div>
<ul class="nav">
    <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="#">Active</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
    </li>
    <li class="nav-item">
        <a class="nav-link disabled">Disabled</a>
    </li>
</ul>

PrimeiraAppWeb_2TDSPF/PrimeiraAppWeb_2TDSPF/Views/Boardgame/Edit.cshtml
@model PrimeiraAppWeb_2TDSPF.Models.Boardgame

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Boardgame</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


PrimeiraAppWeb_2TDSPF/PrimeiraAppWeb_2TDSPF/Views/Boardgame/Index.cshtml
@model IEnumerable<PrimeiraAppWeb_2TDSPF.Models.Boardgame>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row">
    <div class="col-md-3">
        <div id="topGamesContainer">
            <!-- O conteúdo do partial será carregado aqui -->
        </div>
        <script type="text/javascript">
            document.addEventListener("DOMContentLoaded", function() {
                fetch('/Boardgame/TopRatedGames')
                    .then(response => response.text())
                    .then(html => {
                        document.getElementById('topGamesContainer').innerHTML = html;
                    })
                    .catch(error => console.error('Erro ao carregar os jogos mais bem avaliados:', error));
            });
        </script>
    </div>
    <div class="col-md-9">
        <h1>Index</h1>
        <p>
            <a asp-action="Create">Create New</a>
        </p>
        <table class="table">
            <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    </td>
                </tr>
            }
            </tbody>
        </table>
    </div>
</div>



PrimeiraAppWeb_2TDSPF/PrimeiraAppWeb_2TDSPF/Views/Boardgame/_Top.cshtml
@model IEnumerable<PrimeiraAppWeb_2TDSPF.Models.Boardgame>

<div class="card" style="width: 18rem;">
    <div class="card-header">
        Top Games
    </div>
    <ul class="list-group list-group-flush">
        @foreach (var boardgame in Model)
        {
            <li class="list-group-item">
                <a asp-action="Details" asp-route-id="@boardgame.Id">@boardgame.Name</a>
            </li>
        }
    </ul>
</div>

PrimeiraAppWeb_2TDSPF/PrimeiraAppWeb_2TDSPF/Views/Home/Contact.cshtml
@{
    var infoDeContato = "Email: pf1779@fiap.com.br Telefone: 1199999999";
}

<h2>title</h2>
@for(var i = 0; i <=3; i++ ){
    <p>@infoDeContato</p>
}

PrimeiraAppWeb_2TDSPF/PrimeiraAppWeb_2TDSPF/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

PrimeiraAppWeb_2TDSPF/PrimeiraAppWeb_2TDSPF/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - PrimeiraAppWeb_2TDSPF</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/PrimeiraAppWeb_2TDSPF.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PrimeiraAppWeb_2TDSPF</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li>
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
                    </li>
                    <li>
                        <a class="nav-link text-dark" asp-area="" asp-controller="Boardgame" asp-action="Index">Boardgames</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container-fluid">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - PrimeiraAppWeb_2TDSPF - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>